### ISSUE TITLE
Section 3.10 - check index name

### ISSUE THREAD

**Issue by lewiswilliam** [redislabs-training/ru204#22]
FT.CREATE index:bookdemo - this declares that we will be creating an index named `ru204:book:index`.
Please check the index name, it should read `index:bookdemo` rather than `ru204:book:index`

**Comment by simonprickett** [comment]
@lewiswilliam thanks - I'll get this updated.

**Comment by simonprickett** [comment]
This is in 3.1.0.

**Comment by simonprickett** [comment]
Thanks @lewiswilliam this is now fixed and live.
