### ISSUE TITLE
Identical connection files used 

### ISSUE THREAD

**Issue by j8-redis** [redislabs-training/ru204#45]
util/connection.py and week4/util/connection.py both exist and have an empty diff. As such I can't imagine any good reason for having both of them. While I applaud the decision to localize the connection information in a single location, as opposed to other classes, it would nevertheless appear that some housekeeping is in order.

**Comment by simonprickett** [comment]
This is an RU202 issue?  Can you move this issue there please if so, I'm currently overhauling RU202 so will be able to take care of it.
