### ISSUE TITLE
Book 204 gets deleted and is then needed.

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/ru204#8]
Feedback from Discord:

>in 1.4 we delete ru204:book:425, but in 3.1 we need to query the book (`FT.SEARCH index:bookdemo "@title:aftertime")` but of course doesn't exist anymore.

Look into this and correct as needed!

**Comment by justincastilla** [comment]
Updated 3.1 content to search for an alternate book:

<p>Let's run a quick search for the book "Running Out of Time" to verify our documents were indexed properly. To search for the book with the title "Running Out of Time", run this <span class="code"><a href="https://redis.io/commands/ft.search/" target="_blank" class="page-link">FT.SEARCH</a></span> command:
<p><pre class="code">
FT.SEARCH index:bookdemo "@title:(Running Out of Time)"
</pre></p>
<p>Redis returns a response with the number of results matching the search as the first entry. For every entry found, the document key is returned followed by the full document:
<p><pre class="code">
1) "1"
2) "ru204:book:1538"
3) 1) "$"
   2) "{\"author\":\"Margaret Peterson Haddix\",\"id\":\"1538\",\"description\":\"Jessie lives with her family in the frontier village of Clifton, Indiana. When diphtheria strikes the village and the children of Clifton start dying, Jessie's mother sends her on a dangerous mission to bring back help. But beyond the walls of Clifton, Jessie discovers a world even more alien and threatening than she could have imagined, and soon she finds her own life in jeopardy. Can she get help before the children of Clifton, and Jessie herself, run out of time?\",\"editions\":[\"english\",\"spanish\",\"french\"],\"genres\":[\"adventure\",\"childrens\",\"childrens (middle grade)\",\"fiction\",\"historical (historical fiction)\",\"mystery\",\"realistic fiction\",\"science fiction\",\"science fiction (dystopia)\",\"young adult\"],\"inventory\":[{\"status\":\"on_loan\",\"stock_id\":\"1538_1\"},{\"status\":\"available\",\"stock_id\":\"1538_2\"},{\"status\":\"maintenance\",\"stock_id\":\"1538_3\"}],\"metrics\":{\"rating_votes\":23387,\"score\":3.99},\"pages\":544,\"title\":\"Running Out of Time\",\"url\":\"https://www.goodreads.com/book/show/227658.Running_Out_of_Time\",\"year_published\":1995}"
</pre></p>
